pipeline {
  agent none

  stages {
    stage('Build Java App') {
      agent {
        docker {
          image 'maven:3.8.1-openjdk-11'
          args '-v /root/.m2:/root/.m2' // Optional: cache Maven dependencies
        }
      }
      steps {
        dir('backend') {
          sh 'mvn --version'
          sh 'javac HelloWorld.java'
          sh 'java HelloWorld'
        }
      }
    }

    stage('Run Node.js App') {
      agent {
        docker {
          image 'node:16'
        }
      }
      steps {
        dir('frontend') {
          sh 'node --version'
          sh 'npm install'
          sh 'npm start'
        }
      }
    }
  }
}

