pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        // Print Maven version
        sh 'mvn --version'

        // Create a simple HelloWorld.java file
        sh '''
          cat > HelloWorld.java <<EOF
          public class HelloWorld {
              public static void main(String[] args) {
                  System.out.println("Hello World from Java!");
              }
          }
          EOF
        '''

        // Compile and run the Java program
        sh 'javac HelloWorld.java'
        sh 'java HelloWorld'
      }
    }

    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        // Print Node version
        sh 'node --version'

        // Create a simple hello.js file
        sh '''
          cat > hello.js <<EOF
          console.log("Hello World from Node.js!");
          EOF
        '''

        // Run the Node.js program
        sh 'node hello.js'
      }
    }
  }
}
