pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        // Use Maven image that includes OpenJDK
        docker { image 'maven:3.8.1-openjdk-11' }
      }
      steps {
        // Print Maven and Java version
        sh 'mvn --version'
        sh 'java -version'

        // Create a simple HelloWorld.java file
        sh '''
          echo 'public class HelloWorld {
              public static void main(String[] args) {
                  System.out.println("Hello World from Java!");
              }
          }' > HelloWorld.java
        '''

        // Compile and run the Java program
        sh 'javac HelloWorld.java'
        sh 'java HelloWorld'
      }
    }

    stage('Front-end') {
      agent {
        // Use full Node image (not Alpine)
        docker { image 'node:16' }
      }
      steps {
        // Print Node version
        sh 'node --version'

        // Create a simple hello.js file
        sh 'echo "console.log(\\"Hello World from Node.js!\\");" > hello.js'

        // Run the Node.js program
        sh 'node hello.js'
      }
    }
  }
}
